### ISSUE TITLE
Performance of this.containerProps

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/create-scandipwa-app#20]
### Describe the bug

It seems like `this.containerProps` returns new object every time, thus, later when comparing with `===` in PureComponent it always says the objects are different, thus re-render happens.

Maybe we need some shouldUpdate interface there?

**Comment by yeegor** [comment]
This is resolvable with using [@scandipwa/framework](https://www.npmjs.com/package/@scandipwa/framework) package's HOC-related solutions.
