### ISSUE TITLE
Internationalization docs are unclear

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/create-scandipwa-app#21]
### Is your proposal related to a problem?

Translation (internationalization) docs (https://docs.create-scandipwa-app.com/building-your-app/internationalization) are unclear.

### Describe the solution you'd like

I would like them to follow following structure:
- Definition of meaning / function
- Instruction / Example of implementation (step-by-step)
- Other details / reference for in-depth analysis

Please do not forget this package is not available in default CSA. I would add two instructions:
1. Creating new translation bundles (languages)
2. Integrating the `i18n` package

**Comment by yeegor** [comment]
See the new doc here: https://app.gitbook.com/@scandipwa/s/create-scandipwa-app/~/drafts/-MS3UzQk9ij_qyMrnAG3/building-your-app/internationalization/@drafts

**Comment by alfredsgenkins** [comment]
I re-wrote the document, please pay attention to final formatting and structure. It focuses on `guidance` and `definition` first, then optionally provides details on implementation.

Is is published. See - https://docs.create-scandipwa-app.com/building-your-app/internationalization
