### ISSUE TITLE
Non-extractable translations

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/create-scandipwa-app#24]
Following error is displayed upon build:

```
ERROR!

     Non-extractable translations found in your application!
     Consider refactoring them so that they are translatable.
     See a list of files containing them below:
```

The list of non-translatable strings is not supplied. @yeegor this happens on latest version!

**Comment by yeegor** [comment]
Fixed by https://github.com/scandipwa/create-scandipwa-app/pull/26
