### ISSUE TITLE
TypeError: Cannot read property 'defaultLocale' of null

### ISSUE THREAD

**Issue by jerrydkingx** [scandipwa/create-scandipwa-app#27]
Non-extractable translations found in your application!
     Consider refactoring them so that they are translatable.
     See a list of files containing them below:

**Comment by jerrydkingx** [comment]
Specially when executing npm start or npm run start its getting stuck at above error.

**Comment by yeegor** [comment]
This has been fixed in the latest version of `@scandipwa/webpack-i18n-runtime` package.
