### ISSUE TITLE
Reference to React.Component break an app

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/create-scandipwa-app#30]
### Describe the bug

For some reason, potentially for some babel-specific reason the following code: import React from "react"; and then React.Component did not function correctly. Use the import { Component } from "react"; instead. This is a bug, but I am not sure if I will be able to address it soon enough.

The following error is displayed:
```Property name expected type of string but got null```

This can be reproduced from this repo: https://github.com/jherr/scandi-test/pull/1

**Comment by yeegor** [comment]
I believe this is fixed in [Mosaic](https://github.com/tilework/mosaic/tree/master/core/babel-plugin-mosaic-middleware-decorator)
