### ISSUE TITLE
after running npm run start command

### ISSUE THREAD

**Issue by psvasan** [scandipwa/create-scandipwa-app#33]
Failed to compile.

./node_modules/@scandipwa/webpack-i18n-runtime/src/util/localeMap.js
TypeError: Cannot read property 'defaultLocale' of null

ERROR!

     Non-extractable translations found in your application!
     Consider refactoring them so that they are translatable.
     See a list of files containing them below:

**Comment by alfredsgenkins** [comment]
Which command resulted in this? Guessing - the `BUILD_MODE=magento yarn build` one. Indeed issue was present, but got resolve in `@scandipwa/webpack-i18n-runtime@0.0.7` it is now free of this issue.

You can:
1. Upgrade to latest `@scandipwa/scandipwa` will be released at 03.02.2021.
2. Upgrade the package specifically using the: `npm --depth 2 update @scandipwa/webpack-i18n-runtime`
3. Specify the `en_US` locale to compile as follows: https://docs.create-scandipwa-app.com/building-your-app/internationalization#specifying-the-locales-to-compile
