### ISSUE TITLE
not able to configure scandipwa theme for magento website   

### ISSUE THREAD

**Issue by vikasebizon** [scandipwa/create-scandipwa-app#37]
### Describe the bug

I successfully installed pwa app in our magento and able to access with "yarn start". After i build magento theme from "BUILD_MODE=magento yarn build" commend.Now i go to magento admin and set pwa theme for website but not able to configure theme.

**Comment by kabadabra** [comment]
I have the same issue and tried many things. I set up a fresh instance of Magento via Create Magento app, set up a fresh theme via Create ScandiPWA App, did the linking process via `yarn run link <path>` and set the theme in the backend and flushed caches.

Getting the following error on the frontend:

`
1 exception(s):
Exception #0 (InvalidArgumentException): Template "Magento_Theme::scandipwa_root.phtml" is not found

Exception #0 (InvalidArgumentException): Template "Magento_Theme::scandipwa_root.phtml" is not found
<pre>#1 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#2 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#3 ScandiPWA\Customization\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#4 ScandiPWA\Customization\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#5 ScandiPWA\Customization\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/ScandiPWA/Customization/View/Result/Page/Interceptor.php:176]
#6 ScandiPWA\Customization\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#7 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#8 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#9 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>
`

Not sure why it's not running the theme :'(

**Comment by kabadabra** [comment]
I have the same issue running in a multi store environment:

<pre>
Exception #0 (Exception): pwa-root template not found
</pre>

**Comment by rMazeiks** [comment]
> If your theme is not shown, set the type of your theme in the theme Magento table to 4. This is a bug in ScandiPWA that will soon be fixed.

Did you try this?

**Comment by vikasebizon** [comment]
@rMazeiks 
Yes it is already set. 
https://www.dropbox.com/s/0i742oybn1cwniy/Screen%20Shot%28765%29.png?dl=0

**Comment by alfredsgenkins** [comment]
Hello!

I have not check your Dropbox link yet, but:

1. The error is coming from Route717 which is trying to lookup ScandiPWA root template (which is "scandipwa_root.phtml"), and this configuration is set in extension @scandipwa/m2-theme (https://github.com/scandipwa/scandipwa/blob/2843a623d8f8ca5a763cd6fd399523c279c25bd0/packages/m2-theme/build-config/craco.js#L38)

2. If this file is missing, check what is located in that folder, see "magento/Magento_Theme/temaplates" the file specified above should exist there. This file ONLY APPEARS when you build the app in Magento mode => BUILD_MODE=Magento should be set when compiling.

3. The folder created with ScandiPWA should be SYM-LINKED, not just put in app/design. This is required because package content is located in "magento" folder and not directly in the folder root.

**Comment by vikasebizon** [comment]
@alfredsgenkins, 
Thank you for your help. 
I resolve that issue but now i am facing another issue :- 

Call to undefined method ScandiPWA\Customization\View\Result\Page\Interceptor::getLocaleChunkUrl() in /data/web/frontrunner_241/localmodules/pwa/magento/Magento_Theme/templates/scandipwa_root.phtml:54

Call to undefined method ScandiPWA\Customization\View\Result\Page\Interceptor::getLanguageCode() in /var/www/local.frontrunner234.com/multi/localmodules/pwa/magento/Magento_Theme/templates/scandipwa_root.phtml:7

**Comment by alfredsgenkins** [comment]
It definitely seems like your locale composer package is out of date. It must be 2.0 and above.

If nothing you do works, please remove your vendor and composer lock and re-install composer. Sometimes it gets hard-cached.

**Comment by vikasebizon** [comment]
@alfredsgenkins Thank you

**Comment by Amir-Teshome** [comment]
@alfredsgenkins thank you for the comment, when you say "SYM-LINKED using Composer" does it mean to install the generated theme using composer and local repository (i.e., configuring local repo as `composer config repo.theme path ...` and the `composer require ...`)? or  SYM-LINKED is symbolic link (i.e., using `ln` command in Linux)?

**Comment by alfredsgenkins** [comment]
The composer local repository approach, sorry for misleading answer :)

**Comment by Amir-Teshome** [comment]
Thanks again for the comment, I still can't manage to set it up correctly, Now the request for `manifest.json` and some other resources returns 404 (the products seems to be fetched correctly).  any help is appreciated 
![scandi-error](https://user-images.githubusercontent.com/6618929/107805888-4bc18e80-6d66-11eb-86ce-dda0741075bb.jpg)

**Comment by vikasebizon** [comment]
Hello @alfredsgenkins , 
Now we are facing magento multi-store issue. We have store like en/za, en/de, en/au, en/us. Can you please help us how we configure it ?
