### ISSUE TITLE
Problem with setting up scandipwa in VScode

### ISSUE THREAD

**Issue by AdamTakaacs** [scandipwa/create-scandipwa-app#41]
Hello guys so i have an issue I'm trying to setup scandi PWA locally following this guide:https://docs.scandipwa.com/hands-on-tutorials/lets-talk-theory.
I was following the steps but after i run npm start im getting the following error:
`./node_modules/@scandipwa/webpack-i18n-runtime/src/util/localeMap.js
Module not found: Can't resolve 'C:UsersAdamDocumentsCodingscandikesapotlac`
I have no idea what could be the problem i tried different versions of node. Also tried with yarn but nothing seems to work. Thanks for your help it would really help me a lot as I'm using this for my project and I'm stuck on this issue for days now.

**Comment by yeegor** [comment]
This is supposed to be resolved now, after the latest release. Update your deps and try again!
