### ISSUE TITLE
Failed to load config "@scandipwa" to extend from.

### ISSUE THREAD

**Issue by mohan-nishit** [scandipwa/create-scandipwa-app#57]
### Describe the bug

On running BUILD_MODE=magento yarn build or BUILD_MODE=magento yarn start, and also without build mode, getting an error saying:

> Failed to compile.
> 
> Failed to load config "@scandipwa" to extend from.
> Referenced from: BaseConfig

### Did you try recovering your dependencies?

Yes, removed the below, and ran yarn again, and fetched all deps.

    * node_modules
    * package-lock.json
    * yarn.lock

 
  Please paste the output of `npm --version` and/or `yarn --version` to confirm.

> yarn --version
> 1.22.10

### Which terms did you search for in User Guide?

Magento Theme

### Environment

Host is Ubuntu 18.04. 
Node is v14.15.4
NPM is v6.14.13

### Steps to reproduce

For an existing Magento 2.4.2 project, followed the steps mentioned [here](https://docs.scandipwa.com/getting-started-1/storefront-mode) and [here](https://docs.scandipwa.com/getting-started-1/magento-integration)

1. yarn create scandipwa-app my-app
2. cd my-app
3. yarn start

### Expected behavior
Using `BUILD_MODE=magento yarn start`, expected the theme to compile successfully.

### Actual behavior
Got the error:

> Failed to compile.
> 
> Failed to load config "@scandipwa" to extend from.
> Referenced from: BaseConfig

<img width="363" alt="Screenshot 2021-06-24 at 1 37 24 AM" src="https://user-images.githubusercontent.com/8962159/123161187-bd37e900-d48c-11eb-8f23-2f87b828394f.png">

**Comment by sachin000** [comment]
same issue here, for upgraded released version 4.5.0

**Comment by ajeetsonkar** [comment]
Also a same issue here, for upgraded released version 4.5.0

**Comment by ajeetsonkar** [comment]
Hi @mohan-nishit 
Did you find any solution to this issue?

**Comment by ajeetsonkar** [comment]
> ### Describe the bug
> On running BUILD_MODE=magento yarn build or BUILD_MODE=magento yarn start, and also without build mode, getting an error saying:
> 
> > Failed to compile.
> > Failed to load config "@scandipwa" to extend from.
> > Referenced from: BaseConfig
> 
> ### Did you try recovering your dependencies?
> Yes, removed the below, and ran yarn again, and fetched all deps.
> 
> ```
> * node_modules
> * package-lock.json
> * yarn.lock
> ```
> 
> Please paste the output of `npm --version` and/or `yarn --version` to confirm.
> 
> > yarn --version
> > 1.22.10
> 
> ### Which terms did you search for in User Guide?
> Magento Theme
> 
> ### Environment
> Host is Ubuntu 18.04.
> Node is v14.15.4
> NPM is v6.14.13
> 
> ### Steps to reproduce
> For an existing Magento 2.4.2 project, followed the steps mentioned [here](https://docs.scandipwa.com/getting-started-1/storefront-mode) and [here](https://docs.scandipwa.com/getting-started-1/magento-integration)
> 
> 1. yarn create scandipwa-app my-app
> 2. cd my-app
> 3. yarn start
> 
> ### Expected behavior
> Using `BUILD_MODE=magento yarn start`, expected the theme to compile successfully.
> 
> ### Actual behavior
> Got the error:
> 
> > Failed to compile.
> > Failed to load config "@scandipwa" to extend from.
> > Referenced from: BaseConfig
> 
> <img alt="Screenshot 2021-06-24 at 1 37 24 AM" width="363" src="https://user-images.githubusercontent.com/8962159/123161187-bd37e900-d48c-11eb-8f23-2f87b828394f.png">

Hi, Did you find any solution to this issue?

**Comment by GAkim** [comment]
For most of the cases updating eslint-config helps
just run in your theme folder 'scandipwa'
`npm install @scandipwa/eslint-config@latest`

**Comment by alfredsgenkins** [comment]
Please reopen if this did not help.

**Comment by akhileshdhar** [comment]
thanks. working fine
