### ISSUE TITLE
Cannot Build CSA In Magento Mode

### ISSUE THREAD

**Issue by zans-laksa** [scandipwa/create-scandipwa-app#68]
If i build the app in magento mode (`BUILD_MODE=magento yarn run build`), it gives this error:
```
Build completed in 13.81s

Compiled successfully.

File sizes after gzip:

ENOENT: no such file or directory, open '/home/zhan/Projects/ppp/build/static/css/0.d1ed483c.chunk.css'
```

There is no error if i build app without `BUILD_MODE=magento`

```
yarn 1.22.10
npm 6.14.12
@scandipwa/scandipwa 4.5.1
@scandipwa/scandipwa-scripts 2.4.14
@scandipwa/eslint-config 0.1.30
@tilework/mosaic 0.1.4
```

**Comment by LifeAsBook** [comment]
it's a bug.Same situation as you

**Comment by LifeAsBook** [comment]
[root@vultr my-app]# BUILD_MODE=magento yarn build
yarn run v1.22.11
$ scandipwa-scripts build

NOTE!

     Building as a Magento theme!
     The public/index.html file content will not be taken into account!
     Using content of public/index.php instead!

Creating an optimized production build...
  build [======              ] 32%Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Build completed in 22.581s

Compiled successfully.

File sizes after gzip:

ENOENT: no such file or directory, open '/root/my-app/build/static/css/0.d1ed483c.chunk.css'
